apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen       8000;
      server_name  localhost;
      resolver 10.96.0.10;
      set $api "http://api.default.svc.cluster.local:9000/";
    
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    
      location /api {
        proxy_pass $api;
        proxy_redirect off;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
      }
    }
